# Generated by Django 5.1.4 on 2025-05-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_number', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.TextField()),
                ('tahitian', models.TextField()),
                ('mandarin', models.TextField()),
                ('category', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('expression', 'Expression'), ('other', 'Other')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=1)),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='hakkadbapp.final')),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='hakkadbapp.initial')),
                ('tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='hakkadbapp.tone')),
            ],
        ),
        migrations.CreateModel(
            name='VocabList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('words', models.ManyToManyField(related_name='vocab_lists', to='hakkadbapp.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pronunciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.pronunciation')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.word')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciations',
            field=models.ManyToManyField(through='hakkadbapp.WordPronunciation', to='hakkadbapp.pronunciation'),
        ),
        migrations.AddConstraint(
            model_name='pronunciation',
            constraint=models.UniqueConstraint(fields=('hanzi', 'initial', 'final', 'tone'), name='unique_pronunciation_combination'),
        ),
    ]
