# Generated by Django 5.1.4 on 2025-06-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='tone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='hakkadbapp.tone'),
        ),
    ]
