# Generated by Django 5.1.4 on 2025-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0002_alter_pronunciation_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='final',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='initial',
            name='initial',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
