# Generated by Django 5.1.4 on 2025-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0004_traces'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='char_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traces',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
