# Generated by Django 5.2.5 on 2025-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0006_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
