# Generated by Django 5.2.5 on 2025-12-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0007_word_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.TextField(help_text='French translation of the expression')),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.expression')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.word')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('expression', 'position')},
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='words',
            field=models.ManyToManyField(related_name='expressions', through='hakkadbapp.ExpressionWord', to='hakkadbapp.word'),
        ),
    ]
