# Generated by Django 5.2.5 on 2025-12-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0008_expression_expressionword_expression_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='words',
        ),
        migrations.AddField(
            model_name='expression',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.word'),
        ),
    ]
