# Generated by Django 5.2.5 on 2025-12-21 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0009_remove_expression_words_expression_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='word',
        ),
        migrations.AddField(
            model_name='expression',
            name='words',
            field=models.ManyToManyField(related_name='expressions', through='hakkadbapp.ExpressionWord', to='hakkadbapp.word'),
        ),
        migrations.AlterField(
            model_name='expressionword',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hakkadbapp.word'),
        ),
    ]
