# Generated by Django 5.2.5 on 2025-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0010_remove_expression_word_expression_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='text',
            field=models.TextField(blank=True, help_text='space separated words simp', null=True),
        ),
    ]
