# Generated by Django 5.2.5 on 2026-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0011_expression_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='rendering',
            field=models.TextField(blank=True, default='', help_text='pinyin+hanzi', null=True),
        ),
    ]
