# Generated by Django 5.2.5 on 2026-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0012_expression_rendering'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
