# Generated by Django 5.2.5 on 2026-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0013_expression_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='english',
            field=models.TextField(blank=True, default='', help_text='English', null=True),
        ),
    ]
