# Generated by Django 5.1.4 on 2026-09-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkadbapp', '0014_expression_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='platform_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
